using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TitleMenu : MonoBehaviour
{
    [SerializeField] private MenuController menuController;

    bool cursor = false;
    int delayCount = 0;
    void Start()
    {
        cursor = false;
        delayCount = 0;
    }

    private void Update()
    {
        if (!cursor)
        {
            //ˆê“x’x‚ê‚Ä‚©‚ç‚¶‚á‚È‚¢‚Æ³Šm‚ÈUIÀ•W‚ªæ‚ê‚È‚¢‚½‚ß‚±‚Ìˆ—‚É‚µ‚Ä‚Ü‚·
            if (delayCount++ == 1)
            {
                menuController.SelectReset();
                menuController.CursorUse();
                cursor = true;
            }
        }
    }
}
